env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
  -plugin:import/recommended", "plugin:node/recommended", "plugin:promise/recommended"],
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - warn
    - as-needed
