language: node_js

node_js:
    - "16"

services:
  - mysql
  - mongodb

env:
  - NODE_ENV=travis

before_script:
  - sleep 15
  - mongo pet_swap_test --eval 'db.createUser({user:"travis",pwd:"password",roles:["readWrite"]});'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS pet_swap_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install
  - sequelize db:migrate

script:
  - npm run test

after_success:
  - curl -X POST ${RENDER_DEPLOY_HOOK_URL}
